services:
  # Ingesta (Artefacto 2)
  kafka:
    image: ubuntu/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

  # Procesamiento (Artefacto 2)
  spark:
    image: apache/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"

  # Metadatos (Requisitos técnicos)
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: tlc_password
